### ISSUE TITLE
Where my file is rendered?

### ISSUE THREAD

**Issue by jonatasnardi** [Novaleaf/phantomjscloud-node-examples#1]
Hello!

I downloaded the phantomjscloud-node-examples and run the "capture-pdf.js" in my machine. Not appears any error, but not appears the pdf  file in any place. 

I'm running the following: http://i.imgur.com/N5G2DUC.png

Thanks by help! ;)

**Comment by jasonswearingen** [comment]
hi, sorry running the examples was confusing.  I made it simpler and added instructions in the readme.

for example, you can now run `node ./dist/basic/capture-pdf.js`  from the root folder, and a `content.pdf` will be saved to the root folder.

**Comment by jasonswearingen** [comment]
please pull the latest changes i just uploaded :)

**Comment by jonatasnardi** [comment]
It works for me!
Thanks @jasonswearingen =)
