### ISSUE TITLE
Using NodeJS to render PDF.

### ISSUE THREAD

**Issue by nahomtefera** [Novaleaf/phantomjscloud-node-examples#3]
Hello Jason!
I have a website and I want to be able to download that website as PDF using PhantomJs.

However this website is constantly changing, the user is inputing information and I want them to be able to download the website as PDF with the information they submitted.

What do you think would be the best way to do that?

**Comment by jasonswearingen** [comment]
Hi, if you could let me know the URL you are trying to render to pdf, I will paste example code that does what you want.

**Comment by jasonswearingen** [comment]
no followup from user
