### ISSUE TITLE
How do I render a HTML string to PDF?

### ISSUE THREAD

**Issue by AmarPrabhu** [Novaleaf/phantomjscloud-node-examples#5]
Hi Jason, I am unable to figure out how to render HTML strings to PDF/JPEG from the docs.

It would be great if you can help with an example.

**Comment by jasonswearingen** [comment]
i just checked in an example showing this, hope it helps.   please see https://github.com/Novaleaf/phantomjscloud-node-examples/commit/dceb18d2f5b62eed8ebff1004ba981915d3bb192
